Задачи модуль 2
js-tasks-ru/jsbasic-20240115_kalaev pull request #2
Opened 2024-02-04 10:53 UTC by Kalaev

Если есть другие методы понять что ты тормоз,то JavaScript опережает любой из них. Таким тормозом как при решении задач я себя не ощущал.

2024-02-04 10:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-04 19:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-05 14:12 UTC, SinimaWath requested changes

2024-02-05 14:12 UTC, SinimaWath commented on 2-module/1-task/index.js
> +};
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 2-module/1-task/index.js
> +sumSalary(salaries)
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 2-module/2-task/index.js
> +console.log( isEmpty(schedule) );
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 2-module/3-task/index.js
> +console.log(calculator.mul()); // 15
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 2-module/3-task/index.js
> -window.calculator = calculator; // делает ваш калькулятор доступным глобально
Эту строчку надо вернуть

2024-02-05 14:12 UTC, SinimaWath commented on 3-module/1-task/index.js
> +let users = [vasya, petya, masha];
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 3-module/1-task/index.js
> +console.log(names)
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 3-module/2-task/index.js
> +console.log( arr ); // [5,3,8,1] (без изменений)
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 3-module/3-task/index.js
> +camelize('-webkit-transition') == 'WebkitTransition';
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 3-module/5-task/index.js
> +let inputData = '1 и -5.8 или 10 хотя 34 + -5.3 и 73';
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-05 14:12 UTC, SinimaWath commented on 3-module/5-task/index.js
> +console.log(getMinMax(inputData)); // { min: -5.8, max: 73  }
Давай уберем. Надо убрать все лишнее из файла с решением задачи.

2024-02-06 08:07 UTC, Kalaev commented
Исправил ошибки. Понял для себя, что нужно присылать только решение задачи, без вводных данных.

2024-02-06 08:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-08 10:07 UTC, Kalaev commented
Добавил одно исправление

2024-02-08 10:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-08 10:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-09 12:36 UTC, SinimaWath approved these changes
Все круто

2024-02-09 12:37 UTC, merged

2024-02-09 13:34 UTC, Kalaev commented
Спасибо ☺️



Отправлено из мобильной Почты Mail.ru


пятница, 9 февраля 2024 г. в 15:36 +03:00 от ***@***.***  ***@***.***>:
>@SinimaWath approved this pull request.
>Все круто
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <js-tasks-ru/jsbasic-20240115_kalaev/pull/2/review/1872282871 @ github . com>